# Generated by Django 4.2.7 on 2023-11-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('body_mass_index', models.FloatField()),
                ('SPO2', models.IntegerField()),
                ('admission_date', models.DateField()),
                ('result', models.IntegerField()),
            ],
        ),
    ]
