# Generated by Django 5.0 on 2023-12-10 18:49

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_token', models.CharField(default=None, editable=False, max_length=100, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('patronymic', models.CharField(blank=True, default='', max_length=100)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('body_mass_index', models.FloatField(blank=True, null=True)),
                ('spo2', models.IntegerField(blank=True, null=True)),
                ('admission_date', models.DateField()),
                ('result', models.IntegerField(blank=True, null=True)),
                ('gender', models.BooleanField(choices=[(0, 'Женский'), (1, 'Мужской')], default=True)),
                ('f_test_ex', models.IntegerField(blank=True, null=True)),
                ('f_test_in', models.IntegerField(blank=True, null=True)),
                ('comorb_ccc', models.BooleanField(blank=True, default=False)),
                ('comorb_bl', models.BooleanField(blank=True, default=False)),
                ('cd_ozhir', models.BooleanField(blank=True, default=False)),
                ('comorb_all', models.BooleanField(blank=True, default=False)),
                ('l_109', models.FloatField(blank=True, null=True)),
                ('lf', models.IntegerField(blank=True, null=True)),
                ('rox', models.FloatField(blank=True, null=True)),
                ('spo2_fio', models.FloatField(blank=True, null=True)),
                ('ch_d', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalClient',
            fields=[
                ('id_token', models.CharField(db_index=True, default=None, editable=False, max_length=100)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('patronymic', models.CharField(blank=True, default='', max_length=100)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('body_mass_index', models.FloatField(blank=True, null=True)),
                ('spo2', models.IntegerField(blank=True, null=True)),
                ('admission_date', models.DateField()),
                ('result', models.IntegerField(blank=True, null=True)),
                ('gender', models.BooleanField(choices=[(0, 'Женский'), (1, 'Мужской')], default=True)),
                ('f_test_ex', models.IntegerField(blank=True, null=True)),
                ('f_test_in', models.IntegerField(blank=True, null=True)),
                ('comorb_ccc', models.BooleanField(blank=True, default=False)),
                ('comorb_bl', models.BooleanField(blank=True, default=False)),
                ('cd_ozhir', models.BooleanField(blank=True, default=False)),
                ('comorb_all', models.BooleanField(blank=True, default=False)),
                ('l_109', models.FloatField(blank=True, null=True)),
                ('lf', models.IntegerField(blank=True, null=True)),
                ('rox', models.FloatField(blank=True, null=True)),
                ('spo2_fio', models.FloatField(blank=True, null=True)),
                ('ch_d', models.IntegerField(blank=True, null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),#
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical client',
                'verbose_name_plural': 'historical clients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
