# Generated by Django 4.2.7 on 2023-11-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.BooleanField(choices=[(0, 'Female'), (1, 'Male')], default=False),
        ),
    ]
