# Generated by Django 4.2.7 on 2023-11-24 17:21

from django.db import migrations, models
import secrets
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(max_length=100, default=secrets.token_urlsafe, unique=True),
        ),
    ]
