# Generated by Django 4.2.7 on 2023-11-24 17:21

from django.db import migrations, models
import secrets
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='token',
            field=models.CharField(default=secrets.token_urlsafe, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
