# Generated by Django 4.2.7 on 2023-12-01 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import secrets
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0003_client_token_alter_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='SPO2',
        ),
        migrations.AddField(
            model_name='client',
            name='cd_ozhir',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='ch_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='comorb_all',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='comorb_bl',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='comorb_ccc',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='f_test_ex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='f_test_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='l_109',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='lf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='rox',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='spo2_fio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='body_mass_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.BooleanField(choices=[(0, 'Female'), (1, 'Male')], default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='patronymic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='result',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalClient',
            fields=[
                ('token', models.CharField(db_index=True, default=secrets.token_urlsafe, max_length=100)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('patronymic', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('body_mass_index', models.FloatField(blank=True, null=True)),
                ('spo2', models.IntegerField(blank=True, null=True)),
                ('admission_date', models.DateField()),
                ('result', models.IntegerField(blank=True, null=True)),
                ('gender', models.BooleanField(choices=[(0, 'Female'), (1, 'Male')], default=True)),
                ('f_test_ex', models.IntegerField(blank=True, null=True)),
                ('f_test_in', models.IntegerField(blank=True, null=True)),
                ('comorb_ccc', models.BooleanField(blank=True, default=False)),
                ('comorb_bl', models.BooleanField(blank=True, default=False)),
                ('cd_ozhir', models.BooleanField(blank=True, default=False)),
                ('comorb_all', models.BooleanField(blank=True, default=False)),
                ('l_109', models.FloatField(blank=True, null=True)),
                ('lf', models.IntegerField(blank=True, null=True)),
                ('rox', models.FloatField(blank=True, null=True)),
                ('spo2_fio', models.FloatField(blank=True, null=True)),
                ('ch_d', models.IntegerField(blank=True, null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical client',
                'verbose_name_plural': 'historical clients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='client',
            name='spo2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
