# Generated by Django 4.2.7 on 2023-11-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_user'),
    ]

    operations = [
    ]
