# Generated by Django 4.2.7 on 2023-11-24 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20231124_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='temp_field',
            field=models.CharField(default=datetime.datetime(2023, 11, 24, 17, 52, 42, 173989, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
