# Generated by Django 4.2.7 on 2023-11-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='temp_field',
        ),
    ]
