# Generated by Django 4.2.7 on 2023-11-24 18:21

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_client_added_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(default=secrets.token_urlsafe, max_length=100, unique=True),
        ),
    ]
