# Generated by Django 4.2.7 on 2023-11-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='added_user',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
