# Generated by Django 4.2.7 on 2023-11-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_historicalclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalclient',
            name='history_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
