# Generated by Django 4.2.7 on 2023-11-26 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_alter_historicalclient_history_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalclient',
            name='history_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
