name: "Telegram Notification"
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    types: [opened, closed] # Уведомление будет отправлено при открытии или закрытии PR
  create:
    branches:
      - '*' # Уведомление будет отправлено при создании новой ветки

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: "telegram Notification"
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: New 0.1.${{ github.run_id }} version publish