name: "Telegram Notification"
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened] # Уведомление будет отправлено при открытии нового PR
  create:
    branches:
      - '*' # Уведомление будет отправлено при создании новой ветки

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        uses: appleboy/telegram-action@v0.2.0
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "Привет, это сообщение отправлено из GitHub Actions!"
