name: "Telegram Notification"
on:
  pull_request:
    types: [ opened, reopened, edited, closed ]
  pull_request_target:
    types: [ opened, reopened, edited ]
  push:
    branches:
      - main
jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          args: |
            Это сообщение отправлено из GitHub Actions!
            Событие: ${{ github.event_name }} // ${{ github.event.path }}
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref }}
            PR №: ${{ github.event.pull_request.number }}
            New ${{ github.run_id }} version publish